// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmtgckhaegkwyishokjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtdGdja2hhZWdrd3lpc2hva2ptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NzMwNDMsImV4cCI6MjA2NjQ0OTA0M30.pNN1VLI4r5DuKS1v44HxOOGU5QbWY3FJHxBu6LjPWOM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);